### ISSUE TITLE
global name 'base_thing' is not defined in newspaper search

### ISSUE THREAD

**Issue by cvshepherd** [ian-nai/Europeana-Full-Text-in-Python#2]
```
Python 2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from newspaper_search import Search
>>> Search.search('test')
https://newspapers.eanadev.org/api/v2/search.json?query=test&profile=hits&wskey=rnbcowee
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "newspaper_search.py", line 36, in search
    new_url = "".join(base_url2 + '' + base_thing + '' + "/annopage/1")
NameError: global name 'base_thing' is not defined
>>> 
```

I couldn't find `base_thing` being defined anywhere in the code, so I assume it's a bug.
Cheers

**Comment by ian-nai** [comment]
Thanks for catching this!
